before:
  hooks:
    - go get -u -d ./...
builds:
  - 
    main: ./cmd/amass/main.go
    binary: amass
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
  
  - 
    main: ./cmd/amass.netdomains/main.go
    binary: amass.netdomains
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
  
  - 
    main: ./cmd/amass.db/main.go
    binary: amass.db
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
  
  - 
    main: ./cmd/amass.viz/main.go
    binary: amass.viz
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

archive:
  name_template: "amass_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macos
    386: i386
  wrap_in_directory: true
  format: zip
  files:
    - LICENSE
    - README.md
    - wordlists/*
  
checksum:
  name_template: "amass_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^doc:'
    - '^test:'

brew:
  # Reporitory to push the tap to.
  github:
    owner: OWASP
    name: homebrew-amass

  # Your app's homepage.
  # Default is empty.
  homepage: 'https://www.owasp.org/index.php/OWASP_Amass_Project'

  # Your app's description.
  # Default is empty.
  description: 'In-depth DNS Enumeration and Network Mapping'
